return {
  enabled = false,
  collectorBaseUrl = "http://127.0.0.1:8765",
  pollSeconds = 5,
  runtimeMode = "runtime_gated",
  hostedMarkerFile = "/terrain_agent.hosted",
  commandEndpoint = "/command",
  commandAckEndpoint = "/command/ack",
  reportEndpoint = "/report",
  resultEndpoint = "/result",
  publishRoot = "/publish",
  computerName = "fusion_test_01",
  testComputerName = "fusion_test_01",
  primaryComputerName = "fusion_primary_01",
  autoStart = true,
  commandFile = "/terrain_agent.last_command",
  reportFile = "/terrain_agent.last_report.json",
  resultFile = "/terrain_agent.last_result.json",
  pendingReportFile = "/terrain_agent.pending_report.json",
  pendingResultFile = "/terrain_agent.pending_result.json",
  heartbeatFile = "/terrain_agent.heartbeat",
  processedIdsFile = "/terrain_agent.processed_ids.json",
  processedIdsMax = 128,
}
