return {
  enabled = false,
  collectorBaseUrl = "http://127.0.0.1:8765",
  pollSeconds = 5,
  commandEndpoint = "/command",
  reportEndpoint = "/report",
  resultEndpoint = "/result",
  publishRoot = "/publish",
  computerName = "",
  autoStart = true,
  commandFile = "/terrain_agent.last_command",
  reportFile = "/terrain_agent.last_report.json",
  resultFile = "/terrain_agent.last_result.json",
  heartbeatFile = "/terrain_agent.heartbeat",
}
